/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reloj.vista;

import com.reloj.conexion.Multicast;
import com.reloj.conexion.MulticastRecv;
import com.reloj.conexion.Servidor;
import com.reloj.logica.Reloj;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author geoge
 */
public class VistaReloj extends javax.swing.JFrame implements Runnable {

    protected static Reloj r1;
    protected static Boolean[] stoph;
    protected static Thread h1, h2, h3, h4, h5, h6, h7;
    protected static int numHilo;

    /**
     * Creates new form VistaReloj
     */
    public VistaReloj() {
        initComponents();
        stoph = new Boolean[4];
        Arrays.fill(stoph, false);
        numHilo = 0;

        r1 = new Reloj();

        h1 = new Thread(this);
        h2 = new Thread(this);
        h3 = new Thread(this);
        h4 = new Thread(this);
        h5 = new Thread(this);
        h6 = new Thread(this);
        h7 = new Thread(this);

        h1.start();
        h2.start();
        h3.start();
        h4.start();
        h5.start();
        h6.start();
        h7.start();
    }

    //CODIGO DE HILO
    public void iniciarRelojes() {
        hora1.setText(r1.imprimeHora());
    }

    @Override
    public void run() {

        Thread hiloActual = Thread.currentThread();
//        Servidor serv;
        iniciarRelojes();
        try {

            //serv.startServer();
            while (hiloActual == h1 && !h1.isInterrupted()) {
                //serv.startServer();
                r1.pasarTiempo();
                hora1.setText(r1.imprimeHora());
                try {
                    Thread.sleep(1000);
                } catch (Exception e) {

                }

            }

            while (hiloActual == h2 && !h2.isInterrupted()) {
                MulticastRecv recibirHora = new MulticastRecv();
                recibirHora.multicasRecibir();
                r1 = recibirHora.getHora();

                try {
                    Thread.sleep(1000);
                } catch (Exception e) {

                }

            }

        } catch (Exception e) {
            System.out.println("Fallo al conectar con el servidor " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelReloj1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hora1 = new javax.swing.JLabel();
        jBtnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reloj 1");

        hora1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        hora1.setText("jLabel5");
        hora1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hora1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelReloj1Layout = new javax.swing.GroupLayout(jPanelReloj1);
        jPanelReloj1.setLayout(jPanelReloj1Layout);
        jPanelReloj1Layout.setHorizontalGroup(
            jPanelReloj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReloj1Layout.createSequentialGroup()
                .addGroup(jPanelReloj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelReloj1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(jPanelReloj1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(hora1)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanelReloj1Layout.setVerticalGroup(
            jPanelReloj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReloj1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(hora1)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jBtnModificar.setText("Modificar Hora");
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelReloj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jBtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelReloj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hora1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hora1MouseClicked

        stoph[0] = true;
        h1.interrupt();
        h2.interrupt();
        numHilo = 1;
        h1 = new Thread(this);
        h2 = new Thread(this);


        VistaModificacion modificar = new VistaModificacion();
        modificar.setVisible(true);

    }//GEN-LAST:event_hora1MouseClicked

    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed

        Multicast prueba = new Multicast();
        prueba.iniciarMulticastServidor(r1);

    }//GEN-LAST:event_jBtnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaReloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaReloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaReloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaReloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaReloj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel hora1;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelReloj1;
    // End of variables declaration//GEN-END:variables

}
